- name: Check Dist Version
  shell: lsb_release -c -s
  register: release_name

- name: Add Repository singning Key
  become: true
  apt_key: 
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add Postgresql Repository
  become: true
  apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt {{ release_name.stdout }}-pgdg main
    state: present


- name: Update apt cache
  become: true
  apt:
    update_cache: yes
    
- name: Install postgresql
  become: true
  apt:
    name: postgresql
    state: present
# - name: "Install packages"
#   dnf: "name={{ item }} state=present"
#   with_items:
#     - postgresql
#     - postgresql-server

# - name: "Install Python packages"
#   pip: "name={{ item }}  state=present"
#   with_items:
#     - psycopg2-binary
# - name: "Find out if PostgreSQL is initialized"
#   ansible.builtin.stat:
#     path: "/var/lib/pgsql/data/pg_hba.conf"
#   register: postgres_data

# - name: "Initialize PostgreSQL"
#   shell: "postgresql-setup initdb"
#   when: not postgres_data.stat.exists

# - name: "Start and enable services"
#   service: "name={{ item }} state=started enabled=yes"
#   with_items:
#     - postgresql